### ISSUE TITLE
collectionWigetInterface.updateListName does not update list.ritems

### ISSUE THREAD

**Issue by chjj** [angelsanz/pensieve#1]
I was peeking around and noticed `collectionWigetInterface.updateListName()` does not update the list item correctly (list.ritems won't be updated). blessed.List has a method called setItem that would work better.

It does (https://github.com/angelsanz/pensieve/blob/master/src/widgets/CollectionWidget.js):

``` js
updateListName: function(oldName, newName) {
  rawList.getItem(oldName).setContent(newName);

  screen.render();
},
```

This would work better:

``` js
updateListName: function(oldName, newName) {
  rawList.setItem(oldName, newName);

  screen.render();
},
```

**Comment by angelsanz** [comment]
Oh, I see. That makes more sense, thank you!
